test 2

diff --git a/.github/workflows/space-api-ci.yml b/.github/workflows/space-api-ci.yml
--- a/.github/workflows/space-api-ci.yml
+++ b/.github/workflows/space-api-ci.yml
@@ -35,16 +35,26 @@ jobs:
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan -p $SERVER_PORT -H $SERVER_HOST >> ~/.ssh/known_hosts
           
+          scp -P $SERVER_PORT requirements.txt $SERVER_USER@$SERVER_HOST:$SERVER_DIR/
+          
           ssh -p $SERVER_PORT $SERVER_USER@$SERVER_HOST << EOF
             cd $SERVER_DIR || { echo "Failed to navigate to server directory"; exit 1; }
+            
 
+            rm -rf .git
+            
             if [ ! -d ".git" ]; then
-              git clone https://github.com/isatispooya/space-api.git .
+              git clone https://github.com/isatispooya/space-api.git . --quiet
             else
               git pull origin main || { echo "Git pull failed"; exit 1; }
             fi
 
-            pip install -r requirements.txt || { echo "Failed to install requirements"; exit 1; }
+
+            apt-get update && apt-get install -y python3-pip
+            python3 -m pip install --upgrade pip
+            
+            # نصب requirements
+            python3 -m pip install -r requirements.txt || { echo "Failed to install requirements"; exit 1; }
             python3 manage.py makemigrations || { echo "makemigrations failed"; exit 1; }
             python3 manage.py migrate || { echo "migrate failed"; exit 1; }
           EOF
